pragma solidity ^0.5.0;

contract TeacherRate {

	// mapping (bytes32 => uint8) public teacherRatings;

	// bytes32[] teachers;

	//teachers have unique ID, generated upon creation
	//A name, provided upon creation
	//and an array of ratings to be averaged
	struct teacher {
		uint256 id;
		bytes32 f_name;
		bytes32 l_name;
		uint256[] teacherRatings;
		// string[] teacherReviews;
	}

	teacher[] teachers; //array of all teachers

	//This does nothing
	constructor() public {
		// teachers = teacherEntries;
	}

	//pushes a new instance of teacher struct to array of all teachers
	//ID is autogenerated and ratings are an empty dynamic array
	function _createTeacher (bytes32 _fname, bytes32 _lname) public {
		uint256 _id = _generateID();
		teachers.push(teacher({
			id: _id,
			f_name: _fname,
			l_name: _lname,
			teacherRatings: new uint256[](0)
			// teacherReviews: new string[](0)
			})) -1;
	}

	//Generates a new id sequentially 
	function _generateID () view internal returns(uint256) {
		if(teachers.length < 1){
			return 0;
		}
		else return teachers.length;
	}

	//', string memory _review' removed param
	function _submitReview (uint8 _teacherID, uint256 _rating) public {
		if (_rating < 1 || _rating > 5){ //rating must be between 1 and 5
			revert();
		}
		else {
			teachers[_teacherID].teacherRatings.push(_rating) -1;
			// teachers[_teacherID].teacherReviews.push(_review) -1;
		}
	}
	
			
	//returns the average of all ratings of teacher with given ID
	function _getTeacherRatings(uint8 _teacherID) view public returns (uint256) {
		uint256 avg = 0;
		uint256 len = teachers[_teacherID].teacherRatings.length;
		for(uint i =0; i<len; i++){
			avg += teachers[_teacherID].teacherRatings[i];
		}
		avg = avg / len;
		return avg; 
	}

	// function _getTeacherReviews (uint8 _id) view public returns(string[] memory) {
	// 	return teachers[_id].teacherReviews;
	// }
	

	// function _placeVote(bytes32 _teacher) public {
	// 	teacherRatings[_teacher] += 1;
	// }
	
	//returns array of teacher Ids rather than array of structs,
	//which isnt currently supported by solidity
	function _getTeacherIds() view public returns (uint256[] memory){
		uint256[] memory _Ids;
		for(uint i; i < teachers.length; i++){
			_Ids[i] = teachers[i].id;
		}
		return _Ids;
	}
}